### ISSUE TITLE
Can we have a new release please?

### ISSUE THREAD

**Issue by fabien** [ricokahler/next-data-hooks#130]
Even though the `peerDependencies` now include NextJS 12, a new package hasn't been released on npm yet. Thanks!

**Comment by ricokahler** [comment]
you got it. give me a few

**Comment by ricokahler** [comment]
v0.5.1 is out. my apologies. i typically have something like semantic release do this automatically but i have re-done the CI for this lib yet. that will come soon :D

**Comment by fabien** [comment]
@ricokahler thanks! Just noticed that the same goes for `next-plugin-preval` ;-)
