### ISSUE TITLE
Not working with latest Next

### ISSUE THREAD

**Issue by ezekielaquino** [ricokahler/next-data-hooks#58]
Great project! Tried to use it with my project, however, it was failing with an error `Error: Could not find `NextDataHooksContext`. Ensure `NextDataHooksProvider` is configured correctly.`

Tried to debug and ended up cloning the repo and running the example. First run, works (next 10.0.1), then proceeded to update Next to 10.1.3 (latest). Hit the exception

**Comment by ricokahler** [comment]
Can you give a more specific reproduction of the issue? I've also tried cloning the repo using next 10.1.3 and it works on my machine<sup>TM</sup> 😅.

![CleanShot 2021-04-23 at 00 40 04](https://user-images.githubusercontent.com/10551026/115819387-bdecca00-a3cc-11eb-8468-5df1c2d37d00.gif)

Here's what I did:

1. clone repo
2. cd to `examples/next-data-hooks-example`
3. `npm i` then `npm i --save next@latest`
4. `npx next dev`

want to get to the bottom of this asap!

**Comment by ricokahler** [comment]
Hey @ezekielaquino, any update on this?

**Comment by ezekielaquino** [comment]
Hey @ricokahler thanks for the response! I'm still getting on the my current project. going to try to debug / try again with the example you have above. Will report back 🙏 😄

**Comment by ezekielaquino** [comment]
It works (example project), now I can properly learn by doing–– I think I just am using it incorrectly with the structure and all. Will get there! Closing the issue. Thank you so much and again, fantastic project(s)!
